### ISSUE TITLE
EPIC 1 : EAT

### ISSUE THREAD

**Issue by Sbeaubrundiant** [Sbeaubrundiant/My-Kafet-Area#1]
As a Collaborator I want use My K'A so that I can **EAT** :

- [ ] US1 As a Collaborator I want to create an account so that I can log to the app

- [ ] US1-BIS  As a Collaborator I want to be notified about propposed menu so that I can log to the app 

- [ ] US3 As a Collaborator I want to log to the app so that I can consult menus

- [ ] US5  As a Collaborator I want to consult  menus so that I can book a dish 

- [ ] US7 As a Collaborator I want to book a dish so that I can eat

- [ ] US17 As a catering team member I want to consult the reserved menus list so that I can cook

- [ ] US17-BIS As a catering team member I want to be notified about reserved menu so that I can cook

- [ ] US8 As a Collaborator I want to consult Kitchen real-time affluence so that I can choose the best time for me to go to eat
