### ISSUE TITLE
EPIC 2 : Propose menus

### ISSUE THREAD

**Issue by Sbeaubrundiant** [Sbeaubrundiant/My-Kafet-Area#2]
US 17  As a catering member I want to propose menus to calloborators : 

- [ ] US2 As a catering team member I want to Create an account so that I can log to the app
- [ ] US4 As a catering team member I want to log to the app so that I can  edit menus
- [ ] US6 As a catering team member I want to edit  menus so that I can update the menus list
- [ ] US 18  As a Collaborator I want to be notified about proposed menu so that I can consult the updated menus list
