### ISSUE TITLE
Epic 3 : Cook

### ISSUE THREAD

**Issue by Sbeaubrundiant** [Sbeaubrundiant/My-Kafet-Area#3]
As a catering team member I want to consult the reserved menus so that I can **cook**:

- [ ] Epic 2 : Propose menus https://github.com/Sbeaubrundiant/My-Kafet-Area/issues/2

- [ ] US-20 : As a Catering member I want to notified about reserved menus so that I can cook

- [ ] US-17 As a catering team member I want to consult the reserved menus so that I can cook
