### ISSUE TITLE
EPIC 5 : Registration

### ISSUE THREAD

**Issue by Sbeaubrundiant** [Sbeaubrundiant/My-Kafet-Area#37]
- [ ] US #6   [As a Catering team member I want to Create an account so that I can log to the app](https://github.com/Sbeaubrundiant/My-Kafet-Area/issues/6)
- [ ] US #5  [As a Collaborator I want to create an account so that I can log in to the app](https://github.com/Sbeaubrundiant/My-Kafet-Area/issues/5)
- [ ]  US #31 [As a Collaborator I want to log in to the app so that I can reach the collaborator area](https://github.com/Sbeaubrundiant/My-Kafet-Area/issues/31)
