### ISSUE TITLE
EPIC 4 : Satifying

### ISSUE THREAD

**Issue by Sbeaubrundiant** [Sbeaubrundiant/My-Kafet-Area#4]
As a Collaborator I want to be satisfied so that I can recommand the app :

- [ ] US-13 As a Collaborator I want to leave a comment about the lunch I ate so that I can tell how I felt about it

- [ ] US -16 As a catering team member I want to  be notified about posted comment so that I can consult it

- [ ] US-14 AS a catering team member I want to answer a comment so that I can improve collaborators satisfaction

- [ ] US-15 As a Collaborator I want to be notified about comment response so that I can read what the catering team member answered to  me
